version: '2'
services:
  nginx:
    image: nginx:1.11
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx:/data"

  imgmonic:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - nginx

networks:
  default:
    driver: bridge

