version: 2
services:
  nginx:
    image: nginx:1.11
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx:/data"

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"

  imgmonic:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - nginx
      - redis

networks:
  default:
    driver: bridge

